# Generated by Django 5.2.5 on 2025-09-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('departed', 'Departed')], default='active', max_length=10),
        ),
    ]
