# Generated by Django 5.2.5 on 2025-09-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='seats_taken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
