# Generated by Django 5.2.5 on 2025-10-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ride_seats_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('x', models.IntegerField(help_text='X position in SVG layout')),
                ('y', models.IntegerField(help_text='Y position in SVG layout')),
                ('status', models.CharField(choices=[('available', 'Available'), ('taken', 'Taken')], default='available', max_length=10)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='myapp.ride')),
            ],
        ),
    ]
