# Generated by Django 5.2.5 on 2025-10-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('taken', 'Taken')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='y',
            field=models.IntegerField(),
        ),
    ]
