# Generated by Django 5.2.5 on 2025-10-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_seat_status_alter_seat_x_alter_seat_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='seats_taken',
        ),
        migrations.AlterField(
            model_name='ride',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='route',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='seats_available',
            field=models.IntegerField(),
        ),
    ]
