# Generated by Django 5.2.5 on 2025-11-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_driverrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting at Terminal'), ('departed', 'Departed'), ('completed', 'Completed')], default='waiting', max_length=10),
        ),
    ]
