# Generated by Django 5.2.5 on 2025-11-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_ride_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='myapp.ride')),
            ],
            options={
                'verbose_name': 'Ride Location Point',
                'verbose_name_plural': 'Ride Location Points',
                'ordering': ['timestamp'],
            },
        ),
    ]
