# Generated by Django 5.2.5 on 2025-11-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ridelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='start_point',
            field=models.CharField(choices=[('Naval', 'Naval'), ('Ormoc', 'Ormoc'), ('Tacloban', 'Tacloban'), ('Leyte', 'Leyte')], default='Naval', max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='route',
            field=models.CharField(choices=[('Naval', 'Naval'), ('Ormoc', 'Ormoc'), ('Tacloban', 'Tacloban'), ('Leyte', 'Leyte')], max_length=100),
        ),
    ]
