# Generated by Django 5.2.5 on 2025-11-20 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ride_start_point_alter_ride_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_terminal_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='route',
            field=models.CharField(choices=[('NAVAL', 'NAVAL'), ('ORMOC', 'ORMOC'), ('TACLOBAN', 'TACLOBAN'), ('LEYTE', 'LEYTE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_point',
            field=models.CharField(choices=[('NAVAL', 'NAVAL'), ('ORMOC', 'ORMOC'), ('TACLOBAN', 'TACLOBAN'), ('LEYTE', 'LEYTE')], default='Naval', max_length=100),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_terminals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Terminals',
            },
        ),
        migrations.AlterField(
            model_name='ride',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_rides', to='myapp.terminal'),
        ),
    ]
