# Generated by Django 5.2.5 on 2025-11-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_driver_is_terminal_admin_alter_ride_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='pending_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_drivers', to='myapp.terminal'),
        ),
        migrations.AddField(
            model_name='driver',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_drivers', to='myapp.terminal'),
        ),
    ]
