# Generated by Django 5.2.5 on 2025-11-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_driver_pending_terminal_driver_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(help_text="The destination or key route name (e.g., 'Manila to Baguio')", max_length=100)),
                ('start_point', models.CharField(default='[Terminal Name]', help_text='The starting point of the trip.', max_length=100)),
                ('departure_time', models.TimeField(help_text='The exact time of day for departure (e.g., 07:00:00).')),
                ('capacity', models.PositiveIntegerField(default=10, help_text='The maximum number of passengers for this route.')),
                ('recurrence_days', models.CharField(help_text='Days of the week this route runs (e.g., M,T,W,H,F).', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily stop generating rides for this template.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminal', models.ForeignKey(help_text='The terminal managing this schedule template.', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='myapp.terminal')),
            ],
            options={
                'ordering': ['terminal', 'departure_time'],
                'unique_together': {('terminal', 'route', 'departure_time')},
            },
        ),
    ]
