# Generated by Django 5.2.5 on 2025-11-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_scheduletemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='location_name',
            field=models.CharField(default='NAVAL', help_text="The city/place name used as the starting point for schedules (e.g., 'Naval', 'Tacloban').", max_length=100),
        ),
    ]
