# Generated by Django 5.2.5 on 2025-11-20 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_terminal_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='terminal',
        ),
        migrations.AlterField(
            model_name='ride',
            name='terminal',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pending_terminal',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_terminal_admin',
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ScheduleTemplate',
        ),
        migrations.DeleteModel(
            name='Terminal',
        ),
    ]
