# Generated by Django 5.2.5 on 2025-11-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_terminal_manager_remove_driver_terminal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('terminal', models.CharField(choices=[('NAVAL', 'Naval Terminal'), ('ORMOC', 'Ormoc Terminal'), ('TACLOBAN', 'Tacloban Terminal'), ('LEYTE', 'Leyte Terminal')], help_text='Terminal this admin manages', max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Terminal Administrator',
                'verbose_name_plural': 'Terminal Administrators',
            },
        ),
    ]
