# Generated by Django 5.2.5 on 2025-11-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_terminaladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='assigned_terminal',
            field=models.CharField(blank=True, choices=[('NAVAL', 'Naval Terminal'), ('ORMOC', 'Ormoc Terminal'), ('TACLOBAN', 'Tacloban Terminal'), ('LEYTE', 'Leyte Terminal')], help_text='Terminal this driver wants to be assigned to', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='terminal_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='terminal_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for terminal assignment', max_length=20),
        ),
    ]
