# Generated by Django 5.2.5 on 2025-11-21 02:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_driver_assigned_terminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
