# Generated by Django 5.2.5 on 2025-11-21 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_driver_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full terminal name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code (e.g., NAVAL)', max_length=50, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='driver',
            name='assigned_terminal',
            field=models.ForeignKey(blank=True, help_text='Terminal this driver wants to be assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='myapp.terminal'),
        ),
        migrations.AlterField(
            model_name='terminaladmin',
            name='terminal',
            field=models.OneToOneField(help_text='Terminal this admin manages', on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='myapp.terminal'),
        ),
    ]
