# Generated by Django 5.2.5 on 2025-11-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_terminal_alter_driver_assigned_terminal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='terminal',
            field=models.CharField(choices=[('NAVAL', 'Naval Terminal'), ('ORMOC', 'Ormoc Terminal'), ('TACLOBAN', 'Tacloban Terminal'), ('LEYTE', 'Leyte Terminal')], help_text='Terminal this admin manages', max_length=50, unique=True),
        ),
    ]
