# Generated by Django 5.2.5 on 2025-11-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_ride_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminaladmin',
            name='terminal',
            field=models.OneToOneField(blank=True, help_text='Terminal this admin manages', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='myapp.terminal'),
        ),
    ]
