# Generated by Django 5.2.5 on 2025-11-21 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_terminaladmin_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Driver assigned to this scheduled ride', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, help_text='Terminal admin who created this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rides', to='myapp.terminaladmin'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting at Terminal'), ('departed', 'Departed'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='terminal',
            field=models.CharField(max_length=100),
        ),
    ]
